* SSH

** Spring

*** DONE Book: Spring in action(3rd edtion)
     CLOSED: [2014-07-13 Sun 01:57]
     - State "DONE"       from "STARTED"    [2014-07-13 Sun 01:57]

     - Reading complete, but still need more books,examples to get deep understanding
     - TODO Try a sample project using Sprint Security, roles, users, urls store into DB: http://www.cnblogs.com/visoncheng/p/3335768.html
*** DONE Session: Spring Intro
   CLOSED: [2014-09-14 日 11:07]
   - State "DONE"       from "TODO"       [2014-09-14 日 11:07]
  References:
  http://www.slideshare.net/intellibitz/spring-user-guide
  http://www.slideshare.net/dhaval201279/spring-overview?related=1  Presentation #2
  http://www.slideshare.net/clayz/spring-3814785?related=2
  http://www.slideshare.net/pmanvi/spring-framework-overview-ppt-3068245?related=2 Presentation #1
  http://www.slideshare.net/weili_at_slideshare/an-introduction-to-the-spring-framework?related=3 Presentation #0 fun


** Struts/SpringMVC

*** DONE http://blog.csdn.net/sundenskyqq/article/details/8552623
Struts1/Struts2/SpringMVC框架的比较。
写的不错，可以再看一遍。只是SpringMVC方面写的比较粗糙，排版比较差。有时间可以写一篇博客总结一下。

* Java

** Java Server Side
http://blog.csdn.net/sundenskyqq/article/details/8549932
不错，值得再看一遍。Servlet, Listener, Filter, Interceptor区别与联系，主要涉及基本概念、生命周期、作用范围等。
Struts1使用的是Servlet，而Struts2用的是Filter。拦截器其实是Struts或Spring的概念，不是基本的Java Web概念。

http://blog.csdn.net/zs234/article/details/8832343
Filter和Servlet的比较列表

** Great sites for Java
   http://nofluffjuststuff.com/home/main

   JVM languages
   http://medianetwork.oracle.com/video/player/2623645003001

   Install JDK on Ubuntu:
   https://launchpad.net/~webupd8team/+archive/ubuntu/java

   Java vs. Ruby:
   https://www.ruby-lang.org/en/documentation/ruby-from-other-languages/to-ruby-from-java/
   http://carlosbecker.com/posts/twitter-drops-ruby-bullshit/
   http://a-developer-life.blogspot.com/2013/03/ruby-vs-java.html
   http://www.tuicool.com/articles/ZrQBbu
   http://stackoverflow.com/questions/442216/java-or-python-or-ruby-for-web-application
   http://stackoverflow.com/questions/5083292/playframework-vs-ruby-on-rails
   http://blog.codinghorror.com/why-ruby/

   JPA vs. hibernate, myBatis etc.
   http://stackoverflow.com/questions/9881611/whats-the-difference-between-jpa-and-hibernate
   http://stackoverflow.com/questions/17860161/replacing-a-full-orm-jpa-hibernate-by-a-lighter-solution-recommended-pattern
   http://stackoverflow.com/questions/1984548/hibernate-vs-ibatis/15640572#15640572
   http://mybatis.github.io/mybatis-3/getting-started.html

   Java EE Security

   JAAS is lower level security framework, Spring Security is good fit for web application security
   http://stackoverflow.com/questions/628416/jaas-for-human-beings
   Java Security JGSS JSSE SASL
   http://stackoverflow.com/questions/11347304/security-authentication-ssl-vs-sasl/11385658#11385658
   http://docs.oracle.com/javase/7/docs/technotes/guides/security/jgss/tutorials/JGSSvsJSSE.html
   Glassfish uses Metro as Web Services Security
   http://stackoverflow.com/questions/3417659/java-ee-security-which-method-to-use
   If without Spring Security
   http://stackoverflow.com/questions/2206911/best-way-for-user-authentication-on-javaee-6-using-jsf-2-0


   EJB & CDI
   http://stackoverflow.com/questions/13487987/where-to-use-ejb-3-1-and-cdi/13504763#13504763

   Java VS. PHP
   (++++)为什么大型网站前端使用 PHP 后台逻辑用 Java http://www.zhihu.com/question/20314377
   (+)PHP的前端和后端 http://www.zhihu.com/question/20487516
   (+++++)http://buytaert.net/why-php-and-not-java  Greate debate
   Languages performance http://benchmarksgame.alioth.debian.org/u32/which-programs-are-fastest.php


   Quote:
   "But IMHO Java for website development is most often a major overkill."
   "In my opinion, PHP is better for community whereas java is better for enterprise"


*** Java EE learning
**** DONE Java EE tutorial 6 Basics
**** TODO Java EE tutorial 6 Advanced

* Frameworks

** Comparing
http://raibledesigns.com/rd/entry/comparing_jvm_web_frameworks_at
http://static.raibledesigns.com/repository/presentations/ComparingJavaWebFrameworks-ApacheConUS2007.pdf
More recent: http://static.raibledesigns.com/repository/presentations/Comparing_Kick_Ass_Web_Frameworks.pdf
http://stackoverflow.com/questions/353359/struts-or-spring-mvc-or-struts-spring/2271143#2271143
http://stackoverflow.com/questions/5123816/struts2-vs-spring-3
https://spreadsheets.google.com/pub?key=0AtkkDCT2WDMXdC1HOEtnUHpCejJMbUhGeGJWUmh5dVE&hl=en&output=html
http://stackoverflow.com/questions/2084169/choosing-a-java-web-framework-now/2084512#2084512
http://www.web4j.com/Criticisms_Drawbacks_Pitfalls_Spring_Rails_PHP.jsp

* Interview
Differences among String, StringBuffer, and StringBuilder
http://blog.csdn.net/rmn190/article/details/1492013

When checked exception and when unchecked exception?
http://techblog.bozho.net/?p=316
